language: cpp
compiler:
  - clang
  - gcc
dist: trusty
sudo: false
env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    # TODO add -Werror?
    - CXX_FLAGS="-Wall -pedantic"
    # Misc
    - RUN_TESTS=true
    - COVERAGE=false

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..
     - make

matrix:
  include:
    # g++ 5 comes with Ubuntu 16.04 LTS (Xenial Xerus)
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # Newest release
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}
install:
    # Download and build Boost
    - wget -O boost_1_66_0.tar.gz https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.gz
    - tar xzvf boost_1_66_0.tar.gz
    - cd boost_1_66_0/
    - ./bootstrap.sh --with-libraries=program_options,filesystem,system,log
    - ./b2 -d0 link=static threading=multi variant=release
    - ./b2 install -d0
